### ISSUE TITLE
where is the word2vec.txt

### ISSUE THREAD

**Issue by SeekPoint** [shiningliang/CCKS2019-IPRE#1]

**Comment by shiningliang** [comment]
please run
`python pretrain_embedding.py`
 it conducts word segmentation in text.txt and uses word2vec to train word embeddings on segmented file. Finally you will get word2vec.txt.

**Comment by SeekPoint** [comment]
yes, but then:

Traceback (most recent call last):
  File "baseline.py", line 433, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "baseline.py", line 426, in main
    model = Baseline(FLAGS)
  File "baseline.py", line 74, in __init__
    self.word_map, word_embed = self.load_wordVec()
  File "baseline.py", line 98, in load_wordVec
    word_map = load_pkl(os.path.join(self.processed_data_path, 'word_map.pkl'))
  File "/home/ub16c9/ub16_prj/CCKS2019-IPRE/preprocess.py", line 13, in load_pkl
    with open(file_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/processed/word_map.pkl'


how to generates the  word_map.pkl

**Comment by shiningliang** [comment]
> yes, but then:
> 
> Traceback (most recent call last):
> File "baseline.py", line 433, in 
> tf.app.run()
> File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
> _sys.exit(main(argv))
> File "baseline.py", line 426, in main
> model = Baseline(FLAGS)
> File "baseline.py", line 74, in **init**
> self.word_map, word_embed = self.load_wordVec()
> File "baseline.py", line 98, in load_wordVec
> word_map = load_pkl(os.path.join(self.processed_data_path, 'word_map.pkl'))
> File "/home/ub16c9/ub16_prj/CCKS2019-IPRE/preprocess.py", line 13, in load_pkl
> with open(file_path, 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: './data/processed/word_map.pkl'
> 
> how to generates the word_map.pkl

Sorry it's my fault. Please refer the updated readme

**Comment by SeekPoint** [comment]
prep is works
